name: fractals
description: A new Flutter project.
publish_to: 'none'
version: 0.0.2+2

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  image: ^3.0.1
  dynamic_color: ^1.6.9
  url_launcher: ^6.1.10

flutter:
  uses-material-design: true
  assets:
    - assets/data/authors.json